import KnowledgeGraph as KG

g = KG.KnowledgeGraph()
g.add_risk_factors("AIT")
g.add_risk_factors("MSFT")
g.export_graph()
print(g.list_sectors())
print(g.query_by_sector("industrials"))
print(g.list_industries())
print(g.query_by_industries("industrial-distribution"))
print(g.list_companies())
print(g.query_by_ticker("AIT"))
print(g.query_risk_factors("AIT"))
print(g.query_SEC_sentences("AIT"))
print(g.query_SEC_sentences_by_year("AIT", 2010))
print(g.query_SEC_sentences_by_sector("industrials"))
print(g.query_SEC_sentences_by_sector_year("industrials", 2010))
print(g.query_SEC_sentences_by_industry("industrial-distribution"))
print(g.query_SEC_sentences_by_industry_year("industrial-distribution", 2010))
print(g.list_risk_factors())
print(g.query_by_risk_factor("Energy"))
